<a href="https://colab.research.google.com/github/supriyajujjuri/python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy Basics**

In [ ]:
# what is Numpy?----> Num + py -----> Numpy vs Pyspark
#core library for scientific computing in python
# the central object in Numpy is "Numpy Array's"
# what is Numpy array?
""" High performance, multi dimenstional data structure object whics is designed specifically to perform maths operations"""

In [ ]:
# How many types array's do we have?
#1D--> 0 columns and presence of rows(axis = 0)
#2D--> tabular data where it has both rows and columns
#3D--> it is multi dimensional data structure where it has axis = 0, axis = 1, and axis = 2

In [ ]:
#what are all different use cases of numpy?
""" 1. dot product/ inner product
    2. matrix multiplication
    3. element wise matrix product
    4. solving the linear systems
    5. inverse
    6. determinent
    7. choose the random numbers
    8. statistics"""

In [ ]:
# installation of numpy
!pip install numpy

In [ ]:
#import numpy
import numpy as np

In [ ]:
# how can we check the version of numpy
np.__version__

'1.26.4'

central object is array

In [ ]:
l1 = [1,2,3,4]
a = np.array(l1)
print(a)
print(l1)
b = np.array([1,2,3,4,5,6])
print(b)
#difference between list and array?
#list-->[]-->ordered,mutable,allows duplicates
#array-->[]--> ordered,immutable, allows the duplicates

In [ ]:
f = np.array([1,2,3,4,5])
print(f.shape)

(5,)


In [ ]:
a = np.array([1,2,3,4])
print(a)
# i want to know the shape of the array
a.shape  #-->(count_rows,count_columns)
# i want to know element data types in above array?
a.dtype
# i want to know the dimensionally of the array's?
a.ndim
# i want to know total no of elements in array?
a.size
# i want to know the size in bytes, of each element?
a.itemsize

In [ ]:
import numpy as np
b = np.array([2,3,4,5,6])
b.dtype
b.ndim
b.size
b.itemsize

8

essential methods in array

In [ ]:
b  = np.array([1,2,3])
#access the elements by using the index position numbers
print(b[0])
print(b[0:3])
print(b[::-1])
print(b[:])   # default indexing [start[0]:end n+1: step 1]
print(b[::])

In [ ]:
# i want to know the sum of elements in the array
print(sum(b))

In [ ]:
h = np.array([1,2,3,4,5,6,7,8,9])
#print the sum array h
print(sum(h))
print(h.sum())
#find the mean the of the array "h"
print(h.mean())
#find the min number in array h
print(h.min())
#find the max number in the array h
print(h.max())
""" a = ["cat","dog","cat"]
import pandas as pd
df = pd.dataframe(a)
df.mode()"""

In [ ]:
l = [1,2,3,4,5,6,7,8,9]
print(sum(l))
#print(l.sum())   #attrinute error: "list" object has no attribute "sum"
l.append(10)
l

45


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
a = np.array([1,2,3,4,1,2,3,4,1])
print(dir(a))
#Note:- array's don't have mode and median

Arrays vs list

In [ ]:
# add new items in the list by using append method
l = [1,2,3,4,5,6,7,8,9]
l.append(10)
l

In [ ]:
# add new item to the array
a = np.array([1,2,3])
a.append(4)  # Attribute error: "numpy. ndarry" object has no attribute "append"
a

In [ ]:
# replace items
a[0] = 5
print(a)

In [ ]:
#Note:- array's are immutable where in arrys we can replace the items but we can not add or remove in arrays
#so the array's are having fixed memory
#MISD---> multiple input single destination

In [ ]:
# how can we add items in array?
a = np.array([1,2,3])
b = np.append(a,4)
print(b)

In [ ]:
arr = np.array([2,4,8])
c = np.append(arr,10)
print(c)

[ 2  4  8 10]


In [ ]:
name = np.array(['supriya','deepika','uma'])
d = np.append(name,'narayana')
print(d)

['supriya' 'deepika' 'uma' 'narayana']


In [ ]:
e = [1,2,3,4]+np.array(1)
print(e)

[2 3 4 5]


In [ ]:
c = b+np.array(5)
#single number array is adding with each other and every element in array is known as "Broad casting " method
print(c)

[6 7 8 9]


In [ ]:
#vector addition: adding two array having equal number of elements and same dimensions is known vector addition
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a*b)

In [ ]:
l = [1,2,3]
#multiple of 2
for i in l:
  print(i*2,end=" ")

In [ ]:
print(a*2)

In [ ]:
#find the sqrt for arry's
print(a**0.5)

In [ ]:
a = ['apple',a,5.8,4+6j]
b =np.array(a)
print(b)

In [ ]:
b = [2+4j,5+6j]
c = np.array(b)
d = np.insert(b,2,5+6j)
print(d)

[2.+4.j 5.+6.j 5.+6.j]


dot

In [ ]:
a = np.array([1,2])
b = np.array([3,4])
# sum of products of corresponding items
# when apply dot product check the array are same no of elements
dot = 0
for i in range(len(a)):
   dot += a[i]*b[i]
   print(dot)

In [ ]:
#easy methods
dot = np.dot(a,b)
dot

In [ ]:
dot = a.dot(b)
print(dot)

In [ ]:
dot = a@b
print(dot)

In [ ]:
#manul
c = a*b
d = np.sum(c)
print(d)

In [ ]:
import numpy as np

In [ ]:
#create a 1 dimensional array from list
a=[1,2,3]
b = np.array(a)
print(b.ndim)

1


multi dimensional array's

In [ ]:
#create a 2 dimensional array
a = np.array([[1,2,3],[4,5,6]])
print(a.ndim)
print(a)

2
[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.itemsize)
print(a.shape)

8
(2, 3)


In [ ]:
def f(x):
    def f1(*args, **kwargs):
           print("Sanfoundry")
           return x(*args, **kwargs)
    return f1

In [ ]:
def addItem(listParam):
    listParam += [1]

mylist = [1, 2, 3, 4]
addItem(mylist)
print(len(mylist))

5


In [ ]:
x = ['ab', 'cd']
print(list(map(upper, x)))

NameError: name 'upper' is not defined

In [ ]:
elements = [0, 1, 2]
def incr(x):
  return x+1
print(list(map(elements,incr)))

TypeError: 'function' object is not iterable

In [ ]:
#How can i access the elements from array?
#by using the index position number we can access elements in array
#array[row_index value,column index value]
a = np.array([[1,2,3],[4,5,6]])
print(a[0])

[1 2 3]


In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#if i want to access the particular value from particular column and row
print(b[1,1])
print(b[1][1])
# print the "9" from above array
print(b[2,2])
print(b[2][2])

In [ ]:
#slicing:- accessing the range of characters
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(b)
# i want to print the values present at 1st column
print(b[:,0])
#print all the column values in row zero
print(b[0])
#or the below one both are same
print(b[0,:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 4 7]
[1 2 3]
[1 2 3]


Transpose---> change rows into columns and columns into row

In [ ]:
h = np.array([[1,2,3],[4,5,6]])
print(h.shape)

In [ ]:
u = h.T
print(u)

Matrix multiplication

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[3,4],[4,6]])
#Note:- to apply matrix multiplication the arrays has to in same shape
c= a.dot(b)
print(c)
#print(a*b)   # element wise multiplication

In [ ]:
# broadcasting method:-
a = np.array([[1,2],[3,4]])
b = np.array([[2]])
print(a*b)

In [ ]:
d = np.array([[4,5,6],[7,8,9]])
h = d.dot(b)      #inner dimensions has to be matched
print(h)

In [ ]:
A = d.T
A

In [ ]:
H = A.dot(b)
print(H)

In [ ]:
#Note:- when we apply the dot product for 2 dimensional array it has to be in same shape

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[1,2]])
c = a.dot(b)
print(c)

determinent

In [ ]:
a = np.array([[1,2],[3,4]])
# find the determinent of a
#use 'np.linalg.det'
c = np.linalg.det(a)
print(c)
#determinent ------> it means [(1*4)-(2*3)]

inverse

In [ ]:
a = np.array([[1,2],[3,4]])
d= np.linalg.inv(a)
print(d)

diagonal

In [ ]:
c = np.diag(a)
print(c)

In [ ]:
#diagonal on a vector returns diagonal matrix
d = np.diag([1,4])
print(d)

boolean indexing

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.ndim)
print(a.shape)
print(a)
print(a[:,1])

In [ ]:
#print the elements greater than 2 form above array
print(a[a>2])

In [ ]:
#HOW WE CAN APPLY CONDITION IN ARRAY?
#np.where(condition, true, false)
b = np.where(a>2, a, -1)
print(b)

In [ ]:
a = np.array([10,20,30,40,50,60,19,30,31,61])
#compute indices where the condition is true  . number has to divisible with 2
even  = np.argwhere(a%2==0).flatten()
print(even)
#you want to see the values
a_even = a[even]
print(a_even)

*** Revision ***

Reshaping of an array

In [ ]:
#create an array of range of 1 to 7
import numpy as np

In [ ]:
a = np.arange(1,7)
print(a)

In [ ]:
#reshape the above array in to2 rows and 3 columns?
b = a.reshape(2,3)
print(b)

New axis

In [ ]:
#new axis:- used to create new axis in the data
print(a.shape)
d = a[np.newaxis,:] #to reshape the data into particular manner
print(d)

In [ ]:
d.shape

In [ ]:
e = a[:,np.newaxis]
print(e)
e.shape

In [ ]:
# when we are using np.newaxis?
#needed when the model requires the data to be shaped in a certain manner or to reshape the data into particular manner
#Note: Transpose can be applicable for 2d_array

Concatenation

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
#combine or concatenate the above 2 arrays in 1d_array
c = np.concatenate((a,b),axis = None)
print(c)
""" Note:- 1. when axis = None' it returns id array
           2. when 'axis = 0' it adds second array values into rows wise
           3. when 'axis = 1' it adds the second array values into columns side by side
           we can concatenate as many arrays """

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
c = np.array([[9,10],[11,12]])
c = np.concatenate((a,b,c),axis = 0)
print(c)
print(c[2,:])
print(c[:,1])

***Hstack***

In [ ]:
#hstack:- stack array in sequence horizentally and stack is kind of list it is similar to array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
#c = np.concatenate((a,b),axis = None)
c = np.hstack((a,b))
print(c)
c.shape

Vstack:- add the sequence of stack array's vertically

In [ ]:
d = np.vstack((a,b))
d

In [ ]:
d = np.concatenate((a,b),axis = 0)
d

In [ ]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
#d = np.vstack((a,b))
d = np.hstack((a,b))
d

copying

In [ ]:
 a = np.array([1,2,3])
 b = a
 b[0] = 32
 print(b)

In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0]= 6
print(a)
# By using copy() if you make any changes to new array the old array does not change or to save the actual data

Data Types

In [ ]:
# How can you find data types in array?
a = np.array([1,2,3])
a.dtype

In [ ]:
#store the above array in 32bites
a = np.array([1,2,3],dtype = np.int32)
a.dtype

In [ ]:
a = np.array([1,2,3],dtype = np.float32)
a.dtype
a

Generating Arrays

In [ ]:
#generate an array of zeros which is having 2 rows and 3 columns?
a = np.zeros((2,3))
print(a)

In [ ]:
#generate an array of ones which is having 2 rows and 3 columns?
b = np.ones((2,3))
print(b)
b

In [ ]:
#generate an array of specific number with specific rows and values?
d = np.eye(3)
d

In [ ]:
#generate an array of numbers up to 10
e = np.arange(1,11)
print(e)

In [ ]:
#linspace:- splits the data into equalparts
h = np.linspace(0,10,5)
#np.lionspace(start,end,split_count)
h

In [ ]:
import numpy as np

In [ ]:
d = np.eye(3)
print(d)

In [ ]:
a = np.identity(3)
print(a)

In [ ]:
#numpy.eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, device=None, like=None)
#N---> rows
#M --> Count of columns
#K --> index from where the '1' can be set in column index
#print a matrix with 3*5 idetntity matrix
b = np.eye(5,M=5,k=0)
print(b)

In [ ]:
#what is the difference between np.identity and np.eye()
#Np.idenetity--> return 2D arrray with N*N Matrix
#Np.eye()--> return 2D array with N*N matrics and we can customize the no of rows and columns along with index k customisation

In [ ]:
#argwhere,argmin,argmax--> returns the indexes

Random numbers

In [ ]:
import numpy as np
#generate a random numbers uniformly distributed from 0 to 1?
a =  np.random.random((3,2))
print(a)

[[0.56378282 0.63016169]
 [0.97801261 0.72638926]
 [0.44412319 0.49816463]]


In [ ]:
#generate an array which is normally distributed?
#normal distribution means --> mean,median,mode is same and variance is 1
b = np.random.randn(3,2)
print(b)

In [ ]:
print(np.mean(b))
#print(np.median(b))
print(np.var(b))
print(np.std(b))

In [ ]:
#generate random.randn numbers upto 1000 samples and find the mean,variance and standard deviation(std)
c = np.random.randn(1000)
print(c.mean(),c.var(),c.std())

In [ ]:
#generate an random integers from 10 to 20 in the size of 4*4
#random.randint(low, high=None, size=None, dtype=int)
d = np.random.randint(100)
a = np.random.randint(10,size = 4)
c = np.random.randint(10,size=(4,4))
print(d)
print(a)
print(c)
a = np.array([10, 20, 30, 40])
b = np.array([18, 15, 14])
c = np.array([25, 24, 26, 28, 23])

x, y, z = np.ix_(a, b, c)
print(x)
y = np.array([1,2,3,4,5])
print(y.shape)

In [ ]:
d = np.random.randint(10,20,size=(4,4))
print(d)

In [ ]:
#generate a number upto 6 and divide into size of 10
e = np.random.choice(7,size = 10)
print(e)

In [ ]:
l = np.random.choice([1,2,3,4],size = 10)
print(l)

solving linear equations

In [ ]:
#2x1+3y1 = 0
#6x+12y = 5.
a = np.array([[2,3],[6,12]])
b = np.array([0,5])
# ax = B <==>   x = a**-1 b
x = np.linalg.inv(a).dot(b)
print(x)

In [ ]:
#instead use another method
x = np.linalg.solve(a,b)
print(x)

[-2.5         1.66666667]


In [ ]:
import numpy as np